// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
)

type Attachment struct {
	AttachmentID string `json:"attachment_id"`
	MessageID    string `json:"message_id"`
	ChannelID    string `json:"channel_id"`
	AuthorID     string `json:"author_id"`
	Filename     string `json:"filename"`
	ContentType  string `json:"content_type"`
	Size         int64  `json:"size"`
	Url          string `json:"url"`
}

type Channel struct {
	ChannelID string         `json:"channel_id"`
	Name      string         `json:"name"`
	Type      int64          `json:"type"`
	ServerID  sql.NullString `json:"server_id"`
	ParentID  sql.NullString `json:"parent_id"`
	Metadata  sql.NullString `json:"metadata"`
	CreatedAt int64          `json:"created_at"`
	UpdatedAt int64          `json:"updated_at"`
}

type ConfigValue struct {
	Scope       string         `json:"scope"`
	Key         string         `json:"key"`
	Value       string         `json:"value"`
	Type        int64          `json:"type"`
	IsSensitive int64          `json:"is_sensitive"`
	Constraints sql.NullString `json:"constraints"`
	CreatedAt   int64          `json:"created_at"`
	UpdatedAt   int64          `json:"updated_at"`
}

type Embed struct {
	EmbedID      int64          `json:"embed_id"`
	MessageID    string         `json:"message_id"`
	Title        sql.NullString `json:"title"`
	Description  sql.NullString `json:"description"`
	Url          sql.NullString `json:"url"`
	Color        sql.NullInt64  `json:"color"`
	ThumbnailUrl sql.NullString `json:"thumbnail_url"`
	ImageUrl     sql.NullString `json:"image_url"`
}

type EmbedField struct {
	FieldID int64  `json:"field_id"`
	EmbedID int64  `json:"embed_id"`
	Name    string `json:"name"`
	Value   string `json:"value"`
	Inline  int64  `json:"inline"`
}

type Event struct {
	EventID   string         `json:"event_id"`
	EventType string         `json:"event_type"`
	Scope     string         `json:"scope"`
	ActorID   string         `json:"actor_id"`
	Timestamp int64          `json:"timestamp"`
	Payload   sql.NullString `json:"payload"`
	Metadata  sql.NullString `json:"metadata"`
	Sequence  int64          `json:"sequence"`
}

type Message struct {
	MessageID string         `json:"message_id"`
	ChannelID string         `json:"channel_id"`
	AuthorID  string         `json:"author_id"`
	Content   string         `json:"content"`
	CreatedAt int64          `json:"created_at"`
	UpdatedAt int64          `json:"updated_at"`
	ReplyToID sql.NullString `json:"reply_to_id"`
}
