// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.31.1
// source: config_service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetConfigRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Configuration scope (e.g., "server:123", "channel:456", "user:789", "global")
	Scope string `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	// Specific config keys to retrieve (if empty, returns all)
	Keys []string `protobuf:"bytes,2,rep,name=keys,proto3" json:"keys,omitempty"`
	// Include sensitive values (requires admin permissions)
	IncludeSensitive bool `protobuf:"varint,3,opt,name=include_sensitive,json=includeSensitive,proto3" json:"include_sensitive,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetConfigRequest) Reset() {
	*x = GetConfigRequest{}
	mi := &file_config_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigRequest) ProtoMessage() {}

func (x *GetConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigRequest.ProtoReflect.Descriptor instead.
func (*GetConfigRequest) Descriptor() ([]byte, []int) {
	return file_config_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetConfigRequest) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *GetConfigRequest) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *GetConfigRequest) GetIncludeSensitive() bool {
	if x != nil {
		return x.IncludeSensitive
	}
	return false
}

type GetConfigResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Configuration values
	Configs map[string]*ConfigValue `protobuf:"bytes,1,rep,name=configs,proto3" json:"configs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Scope that was queried
	Scope string `protobuf:"bytes,2,opt,name=scope,proto3" json:"scope,omitempty"`
	// Timestamp when configs were last updated
	LastUpdated   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigResponse) Reset() {
	*x = GetConfigResponse{}
	mi := &file_config_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigResponse) ProtoMessage() {}

func (x *GetConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_config_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigResponse.ProtoReflect.Descriptor instead.
func (*GetConfigResponse) Descriptor() ([]byte, []int) {
	return file_config_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetConfigResponse) GetConfigs() map[string]*ConfigValue {
	if x != nil {
		return x.Configs
	}
	return nil
}

func (x *GetConfigResponse) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *GetConfigResponse) GetLastUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUpdated
	}
	return nil
}

type ListConfigsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Configuration scope
	Scope string `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	// Filter by config key prefix
	KeyPrefix string `protobuf:"bytes,2,opt,name=key_prefix,json=keyPrefix,proto3" json:"key_prefix,omitempty"`
	// Include metadata about each config
	IncludeMetadata bool `protobuf:"varint,3,opt,name=include_metadata,json=includeMetadata,proto3" json:"include_metadata,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListConfigsRequest) Reset() {
	*x = ListConfigsRequest{}
	mi := &file_config_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConfigsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConfigsRequest) ProtoMessage() {}

func (x *ListConfigsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConfigsRequest.ProtoReflect.Descriptor instead.
func (*ListConfigsRequest) Descriptor() ([]byte, []int) {
	return file_config_service_proto_rawDescGZIP(), []int{2}
}

func (x *ListConfigsRequest) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *ListConfigsRequest) GetKeyPrefix() string {
	if x != nil {
		return x.KeyPrefix
	}
	return ""
}

func (x *ListConfigsRequest) GetIncludeMetadata() bool {
	if x != nil {
		return x.IncludeMetadata
	}
	return false
}

type ListConfigsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Available configuration keys with metadata
	Configs []*ConfigInfo `protobuf:"bytes,1,rep,name=configs,proto3" json:"configs,omitempty"`
	// Total count of configs in scope
	TotalCount    int32 `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConfigsResponse) Reset() {
	*x = ListConfigsResponse{}
	mi := &file_config_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConfigsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConfigsResponse) ProtoMessage() {}

func (x *ListConfigsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_config_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConfigsResponse.ProtoReflect.Descriptor instead.
func (*ListConfigsResponse) Descriptor() ([]byte, []int) {
	return file_config_service_proto_rawDescGZIP(), []int{3}
}

func (x *ListConfigsResponse) GetConfigs() []*ConfigInfo {
	if x != nil {
		return x.Configs
	}
	return nil
}

func (x *ListConfigsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type SetConfigRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Configuration scope
	Scope string `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	// Configuration key
	Key string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	// New configuration value
	Value *ConfigValue `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	// Optional description of the change
	Description   string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetConfigRequest) Reset() {
	*x = SetConfigRequest{}
	mi := &file_config_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetConfigRequest) ProtoMessage() {}

func (x *SetConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetConfigRequest.ProtoReflect.Descriptor instead.
func (*SetConfigRequest) Descriptor() ([]byte, []int) {
	return file_config_service_proto_rawDescGZIP(), []int{4}
}

func (x *SetConfigRequest) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *SetConfigRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SetConfigRequest) GetValue() *ConfigValue {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *SetConfigRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type SetConfigResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Success status
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Previous value (if any)
	PreviousValue *ConfigValue `protobuf:"bytes,2,opt,name=previous_value,json=previousValue,proto3" json:"previous_value,omitempty"`
	// Event ID of the published config.updated event
	EventId       string `protobuf:"bytes,3,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetConfigResponse) Reset() {
	*x = SetConfigResponse{}
	mi := &file_config_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetConfigResponse) ProtoMessage() {}

func (x *SetConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_config_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetConfigResponse.ProtoReflect.Descriptor instead.
func (*SetConfigResponse) Descriptor() ([]byte, []int) {
	return file_config_service_proto_rawDescGZIP(), []int{5}
}

func (x *SetConfigResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SetConfigResponse) GetPreviousValue() *ConfigValue {
	if x != nil {
		return x.PreviousValue
	}
	return nil
}

func (x *SetConfigResponse) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

type DeleteConfigRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Configuration scope
	Scope string `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	// Configuration key to delete
	Key string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	// Optional reason for deletion
	Reason        string `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteConfigRequest) Reset() {
	*x = DeleteConfigRequest{}
	mi := &file_config_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteConfigRequest) ProtoMessage() {}

func (x *DeleteConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteConfigRequest.ProtoReflect.Descriptor instead.
func (*DeleteConfigRequest) Descriptor() ([]byte, []int) {
	return file_config_service_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteConfigRequest) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *DeleteConfigRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *DeleteConfigRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type DeleteConfigResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Success status
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Deleted value
	DeletedValue *ConfigValue `protobuf:"bytes,2,opt,name=deleted_value,json=deletedValue,proto3" json:"deleted_value,omitempty"`
	// Event ID of the published config.deleted event
	EventId       string `protobuf:"bytes,3,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteConfigResponse) Reset() {
	*x = DeleteConfigResponse{}
	mi := &file_config_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteConfigResponse) ProtoMessage() {}

func (x *DeleteConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_config_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteConfigResponse.ProtoReflect.Descriptor instead.
func (*DeleteConfigResponse) Descriptor() ([]byte, []int) {
	return file_config_service_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteConfigResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteConfigResponse) GetDeletedValue() *ConfigValue {
	if x != nil {
		return x.DeletedValue
	}
	return nil
}

func (x *DeleteConfigResponse) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

type ConfigInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Configuration key
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// Value type
	Type ConfigValueType `protobuf:"varint,2,opt,name=type,proto3,enum=fuwa.ConfigValueType" json:"type,omitempty"`
	// Human-readable description
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// Default value
	DefaultValue *ConfigValue `protobuf:"bytes,4,opt,name=default_value,json=defaultValue,proto3" json:"default_value,omitempty"`
	// Whether this config is sensitive
	IsSensitive bool `protobuf:"varint,5,opt,name=is_sensitive,json=isSensitive,proto3" json:"is_sensitive,omitempty"`
	// Validation constraints
	Constraints *ConfigConstraints `protobuf:"bytes,6,opt,name=constraints,proto3" json:"constraints,omitempty"`
	// When this config was created
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// When this config was last updated
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// Who last updated this config
	UpdatedBy     string `protobuf:"bytes,9,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigInfo) Reset() {
	*x = ConfigInfo{}
	mi := &file_config_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigInfo) ProtoMessage() {}

func (x *ConfigInfo) ProtoReflect() protoreflect.Message {
	mi := &file_config_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigInfo.ProtoReflect.Descriptor instead.
func (*ConfigInfo) Descriptor() ([]byte, []int) {
	return file_config_service_proto_rawDescGZIP(), []int{8}
}

func (x *ConfigInfo) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ConfigInfo) GetType() ConfigValueType {
	if x != nil {
		return x.Type
	}
	return ConfigValueType_CONFIG_VALUE_TYPE_UNSPECIFIED
}

func (x *ConfigInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ConfigInfo) GetDefaultValue() *ConfigValue {
	if x != nil {
		return x.DefaultValue
	}
	return nil
}

func (x *ConfigInfo) GetIsSensitive() bool {
	if x != nil {
		return x.IsSensitive
	}
	return false
}

func (x *ConfigInfo) GetConstraints() *ConfigConstraints {
	if x != nil {
		return x.Constraints
	}
	return nil
}

func (x *ConfigInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ConfigInfo) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *ConfigInfo) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

var File_config_service_proto protoreflect.FileDescriptor

const file_config_service_proto_rawDesc = "" +
	"\n" +
	"\x14config_service.proto\x12\x04fuwa\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\vtypes.proto\"i\n" +
	"\x10GetConfigRequest\x12\x14\n" +
	"\x05scope\x18\x01 \x01(\tR\x05scope\x12\x12\n" +
	"\x04keys\x18\x02 \x03(\tR\x04keys\x12+\n" +
	"\x11include_sensitive\x18\x03 \x01(\bR\x10includeSensitive\"\xf7\x01\n" +
	"\x11GetConfigResponse\x12>\n" +
	"\aconfigs\x18\x01 \x03(\v2$.fuwa.GetConfigResponse.ConfigsEntryR\aconfigs\x12\x14\n" +
	"\x05scope\x18\x02 \x01(\tR\x05scope\x12=\n" +
	"\flast_updated\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\vlastUpdated\x1aM\n" +
	"\fConfigsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12'\n" +
	"\x05value\x18\x02 \x01(\v2\x11.fuwa.ConfigValueR\x05value:\x028\x01\"t\n" +
	"\x12ListConfigsRequest\x12\x14\n" +
	"\x05scope\x18\x01 \x01(\tR\x05scope\x12\x1d\n" +
	"\n" +
	"key_prefix\x18\x02 \x01(\tR\tkeyPrefix\x12)\n" +
	"\x10include_metadata\x18\x03 \x01(\bR\x0fincludeMetadata\"b\n" +
	"\x13ListConfigsResponse\x12*\n" +
	"\aconfigs\x18\x01 \x03(\v2\x10.fuwa.ConfigInfoR\aconfigs\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"\x85\x01\n" +
	"\x10SetConfigRequest\x12\x14\n" +
	"\x05scope\x18\x01 \x01(\tR\x05scope\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12'\n" +
	"\x05value\x18\x03 \x01(\v2\x11.fuwa.ConfigValueR\x05value\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\"\x82\x01\n" +
	"\x11SetConfigResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x128\n" +
	"\x0eprevious_value\x18\x02 \x01(\v2\x11.fuwa.ConfigValueR\rpreviousValue\x12\x19\n" +
	"\bevent_id\x18\x03 \x01(\tR\aeventId\"U\n" +
	"\x13DeleteConfigRequest\x12\x14\n" +
	"\x05scope\x18\x01 \x01(\tR\x05scope\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"\x83\x01\n" +
	"\x14DeleteConfigResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x126\n" +
	"\rdeleted_value\x18\x02 \x01(\v2\x11.fuwa.ConfigValueR\fdeletedValue\x12\x19\n" +
	"\bevent_id\x18\x03 \x01(\tR\aeventId\"\x96\x03\n" +
	"\n" +
	"ConfigInfo\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12)\n" +
	"\x04type\x18\x02 \x01(\x0e2\x15.fuwa.ConfigValueTypeR\x04type\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x126\n" +
	"\rdefault_value\x18\x04 \x01(\v2\x11.fuwa.ConfigValueR\fdefaultValue\x12!\n" +
	"\fis_sensitive\x18\x05 \x01(\bR\visSensitive\x129\n" +
	"\vconstraints\x18\x06 \x01(\v2\x17.fuwa.ConfigConstraintsR\vconstraints\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1d\n" +
	"\n" +
	"updated_by\x18\t \x01(\tR\tupdatedBy2\x96\x02\n" +
	"\rConfigService\x12<\n" +
	"\tGetConfig\x12\x16.fuwa.GetConfigRequest\x1a\x17.fuwa.GetConfigResponse\x12B\n" +
	"\vListConfigs\x12\x18.fuwa.ListConfigsRequest\x1a\x19.fuwa.ListConfigsResponse\x12<\n" +
	"\tSetConfig\x12\x16.fuwa.SetConfigRequest\x1a\x17.fuwa.SetConfigResponse\x12E\n" +
	"\fDeleteConfig\x12\x19.fuwa.DeleteConfigRequest\x1a\x1a.fuwa.DeleteConfigResponseB\"Z github.com/waifu-devs/fuwa/protob\x06proto3"

var (
	file_config_service_proto_rawDescOnce sync.Once
	file_config_service_proto_rawDescData []byte
)

func file_config_service_proto_rawDescGZIP() []byte {
	file_config_service_proto_rawDescOnce.Do(func() {
		file_config_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_config_service_proto_rawDesc), len(file_config_service_proto_rawDesc)))
	})
	return file_config_service_proto_rawDescData
}

var file_config_service_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_config_service_proto_goTypes = []any{
	(*GetConfigRequest)(nil),      // 0: fuwa.GetConfigRequest
	(*GetConfigResponse)(nil),     // 1: fuwa.GetConfigResponse
	(*ListConfigsRequest)(nil),    // 2: fuwa.ListConfigsRequest
	(*ListConfigsResponse)(nil),   // 3: fuwa.ListConfigsResponse
	(*SetConfigRequest)(nil),      // 4: fuwa.SetConfigRequest
	(*SetConfigResponse)(nil),     // 5: fuwa.SetConfigResponse
	(*DeleteConfigRequest)(nil),   // 6: fuwa.DeleteConfigRequest
	(*DeleteConfigResponse)(nil),  // 7: fuwa.DeleteConfigResponse
	(*ConfigInfo)(nil),            // 8: fuwa.ConfigInfo
	nil,                           // 9: fuwa.GetConfigResponse.ConfigsEntry
	(*timestamppb.Timestamp)(nil), // 10: google.protobuf.Timestamp
	(*ConfigValue)(nil),           // 11: fuwa.ConfigValue
	(ConfigValueType)(0),          // 12: fuwa.ConfigValueType
	(*ConfigConstraints)(nil),     // 13: fuwa.ConfigConstraints
}
var file_config_service_proto_depIdxs = []int32{
	9,  // 0: fuwa.GetConfigResponse.configs:type_name -> fuwa.GetConfigResponse.ConfigsEntry
	10, // 1: fuwa.GetConfigResponse.last_updated:type_name -> google.protobuf.Timestamp
	8,  // 2: fuwa.ListConfigsResponse.configs:type_name -> fuwa.ConfigInfo
	11, // 3: fuwa.SetConfigRequest.value:type_name -> fuwa.ConfigValue
	11, // 4: fuwa.SetConfigResponse.previous_value:type_name -> fuwa.ConfigValue
	11, // 5: fuwa.DeleteConfigResponse.deleted_value:type_name -> fuwa.ConfigValue
	12, // 6: fuwa.ConfigInfo.type:type_name -> fuwa.ConfigValueType
	11, // 7: fuwa.ConfigInfo.default_value:type_name -> fuwa.ConfigValue
	13, // 8: fuwa.ConfigInfo.constraints:type_name -> fuwa.ConfigConstraints
	10, // 9: fuwa.ConfigInfo.created_at:type_name -> google.protobuf.Timestamp
	10, // 10: fuwa.ConfigInfo.updated_at:type_name -> google.protobuf.Timestamp
	11, // 11: fuwa.GetConfigResponse.ConfigsEntry.value:type_name -> fuwa.ConfigValue
	0,  // 12: fuwa.ConfigService.GetConfig:input_type -> fuwa.GetConfigRequest
	2,  // 13: fuwa.ConfigService.ListConfigs:input_type -> fuwa.ListConfigsRequest
	4,  // 14: fuwa.ConfigService.SetConfig:input_type -> fuwa.SetConfigRequest
	6,  // 15: fuwa.ConfigService.DeleteConfig:input_type -> fuwa.DeleteConfigRequest
	1,  // 16: fuwa.ConfigService.GetConfig:output_type -> fuwa.GetConfigResponse
	3,  // 17: fuwa.ConfigService.ListConfigs:output_type -> fuwa.ListConfigsResponse
	5,  // 18: fuwa.ConfigService.SetConfig:output_type -> fuwa.SetConfigResponse
	7,  // 19: fuwa.ConfigService.DeleteConfig:output_type -> fuwa.DeleteConfigResponse
	16, // [16:20] is the sub-list for method output_type
	12, // [12:16] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_config_service_proto_init() }
func file_config_service_proto_init() {
	if File_config_service_proto != nil {
		return
	}
	file_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_config_service_proto_rawDesc), len(file_config_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_config_service_proto_goTypes,
		DependencyIndexes: file_config_service_proto_depIdxs,
		MessageInfos:      file_config_service_proto_msgTypes,
	}.Build()
	File_config_service_proto = out.File
	file_config_service_proto_goTypes = nil
	file_config_service_proto_depIdxs = nil
}
