// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.31.1
// source: types.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Channel types
type ChannelType int32

const (
	ChannelType_CHANNEL_TYPE_UNSPECIFIED  ChannelType = 0
	ChannelType_CHANNEL_TYPE_TEXT         ChannelType = 1
	ChannelType_CHANNEL_TYPE_VOICE        ChannelType = 2
	ChannelType_CHANNEL_TYPE_ANNOUNCEMENT ChannelType = 3
	ChannelType_CHANNEL_TYPE_THREAD       ChannelType = 4
)

// Enum value maps for ChannelType.
var (
	ChannelType_name = map[int32]string{
		0: "CHANNEL_TYPE_UNSPECIFIED",
		1: "CHANNEL_TYPE_TEXT",
		2: "CHANNEL_TYPE_VOICE",
		3: "CHANNEL_TYPE_ANNOUNCEMENT",
		4: "CHANNEL_TYPE_THREAD",
	}
	ChannelType_value = map[string]int32{
		"CHANNEL_TYPE_UNSPECIFIED":  0,
		"CHANNEL_TYPE_TEXT":         1,
		"CHANNEL_TYPE_VOICE":        2,
		"CHANNEL_TYPE_ANNOUNCEMENT": 3,
		"CHANNEL_TYPE_THREAD":       4,
	}
)

func (x ChannelType) Enum() *ChannelType {
	p := new(ChannelType)
	*p = x
	return p
}

func (x ChannelType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChannelType) Descriptor() protoreflect.EnumDescriptor {
	return file_types_proto_enumTypes[0].Descriptor()
}

func (ChannelType) Type() protoreflect.EnumType {
	return &file_types_proto_enumTypes[0]
}

func (x ChannelType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChannelType.Descriptor instead.
func (ChannelType) EnumDescriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{0}
}

type ConfigValueType int32

const (
	ConfigValueType_CONFIG_VALUE_TYPE_UNSPECIFIED ConfigValueType = 0
	ConfigValueType_CONFIG_VALUE_TYPE_STRING      ConfigValueType = 1
	ConfigValueType_CONFIG_VALUE_TYPE_INT         ConfigValueType = 2
	ConfigValueType_CONFIG_VALUE_TYPE_FLOAT       ConfigValueType = 3
	ConfigValueType_CONFIG_VALUE_TYPE_BOOL        ConfigValueType = 4
	ConfigValueType_CONFIG_VALUE_TYPE_OBJECT      ConfigValueType = 5
	ConfigValueType_CONFIG_VALUE_TYPE_ARRAY       ConfigValueType = 6
)

// Enum value maps for ConfigValueType.
var (
	ConfigValueType_name = map[int32]string{
		0: "CONFIG_VALUE_TYPE_UNSPECIFIED",
		1: "CONFIG_VALUE_TYPE_STRING",
		2: "CONFIG_VALUE_TYPE_INT",
		3: "CONFIG_VALUE_TYPE_FLOAT",
		4: "CONFIG_VALUE_TYPE_BOOL",
		5: "CONFIG_VALUE_TYPE_OBJECT",
		6: "CONFIG_VALUE_TYPE_ARRAY",
	}
	ConfigValueType_value = map[string]int32{
		"CONFIG_VALUE_TYPE_UNSPECIFIED": 0,
		"CONFIG_VALUE_TYPE_STRING":      1,
		"CONFIG_VALUE_TYPE_INT":         2,
		"CONFIG_VALUE_TYPE_FLOAT":       3,
		"CONFIG_VALUE_TYPE_BOOL":        4,
		"CONFIG_VALUE_TYPE_OBJECT":      5,
		"CONFIG_VALUE_TYPE_ARRAY":       6,
	}
)

func (x ConfigValueType) Enum() *ConfigValueType {
	p := new(ConfigValueType)
	*p = x
	return p
}

func (x ConfigValueType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConfigValueType) Descriptor() protoreflect.EnumDescriptor {
	return file_types_proto_enumTypes[1].Descriptor()
}

func (ConfigValueType) Type() protoreflect.EnumType {
	return &file_types_proto_enumTypes[1]
}

func (x ConfigValueType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConfigValueType.Descriptor instead.
func (ConfigValueType) EnumDescriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{1}
}

// The core event primitive - everything in Fuwa is an event
type Event struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique event identifier
	EventId string `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	// Event type (e.g., "channel.created", "message.sent", "user.joined")
	EventType string `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	// Event scope/namespace for filtering (e.g., "server:123", "channel:456")
	Scope string `protobuf:"bytes,3,opt,name=scope,proto3" json:"scope,omitempty"`
	// User/service that triggered the event
	ActorId string `protobuf:"bytes,4,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	// When the event occurred
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Event-specific data
	Payload *anypb.Any `protobuf:"bytes,6,opt,name=payload,proto3" json:"payload,omitempty"`
	// Optional metadata for routing/filtering
	Metadata map[string]string `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Sequence number for ordering within a scope
	Sequence      int64 `protobuf:"varint,8,opt,name=sequence,proto3" json:"sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *Event) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *Event) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *Event) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *Event) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Event) GetPayload() *anypb.Any {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Event) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Event) GetSequence() int64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

type Channel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          ChannelType            `protobuf:"varint,3,opt,name=type,proto3,enum=fuwa.ChannelType" json:"type,omitempty"`
	ServerId      string                 `protobuf:"bytes,4,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	ParentId      string                 `protobuf:"bytes,5,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"` // For threads/categories
	Metadata      map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Channel) Reset() {
	*x = Channel{}
	mi := &file_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Channel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Channel) ProtoMessage() {}

func (x *Channel) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Channel.ProtoReflect.Descriptor instead.
func (*Channel) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{1}
}

func (x *Channel) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *Channel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Channel) GetType() ChannelType {
	if x != nil {
		return x.Type
	}
	return ChannelType_CHANNEL_TYPE_UNSPECIFIED
}

func (x *Channel) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *Channel) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *Channel) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Channel) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Channel) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	ChannelId     string                 `protobuf:"bytes,2,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	AuthorId      string                 `protobuf:"bytes,3,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Attachments   []*Attachment          `protobuf:"bytes,5,rep,name=attachments,proto3" json:"attachments,omitempty"`
	Embeds        []*Embed               `protobuf:"bytes,6,rep,name=embeds,proto3" json:"embeds,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	ReplyToId     string                 `protobuf:"bytes,9,opt,name=reply_to_id,json=replyToId,proto3" json:"reply_to_id,omitempty"` // For message replies
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{2}
}

func (x *Message) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *Message) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *Message) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

func (x *Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Message) GetAttachments() []*Attachment {
	if x != nil {
		return x.Attachments
	}
	return nil
}

func (x *Message) GetEmbeds() []*Embed {
	if x != nil {
		return x.Embeds
	}
	return nil
}

func (x *Message) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Message) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Message) GetReplyToId() string {
	if x != nil {
		return x.ReplyToId
	}
	return ""
}

type Attachment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AttachmentId  string                 `protobuf:"bytes,1,opt,name=attachment_id,json=attachmentId,proto3" json:"attachment_id,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	ContentType   string                 `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Size          int64                  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	Url           string                 `protobuf:"bytes,5,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Attachment) Reset() {
	*x = Attachment{}
	mi := &file_types_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Attachment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attachment) ProtoMessage() {}

func (x *Attachment) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attachment.ProtoReflect.Descriptor instead.
func (*Attachment) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{3}
}

func (x *Attachment) GetAttachmentId() string {
	if x != nil {
		return x.AttachmentId
	}
	return ""
}

func (x *Attachment) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *Attachment) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *Attachment) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Attachment) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type Embed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	Color         int32                  `protobuf:"varint,4,opt,name=color,proto3" json:"color,omitempty"`
	Fields        []*EmbedField          `protobuf:"bytes,5,rep,name=fields,proto3" json:"fields,omitempty"`
	ThumbnailUrl  string                 `protobuf:"bytes,6,opt,name=thumbnail_url,json=thumbnailUrl,proto3" json:"thumbnail_url,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,7,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Embed) Reset() {
	*x = Embed{}
	mi := &file_types_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Embed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Embed) ProtoMessage() {}

func (x *Embed) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Embed.ProtoReflect.Descriptor instead.
func (*Embed) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{4}
}

func (x *Embed) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Embed) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Embed) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Embed) GetColor() int32 {
	if x != nil {
		return x.Color
	}
	return 0
}

func (x *Embed) GetFields() []*EmbedField {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *Embed) GetThumbnailUrl() string {
	if x != nil {
		return x.ThumbnailUrl
	}
	return ""
}

func (x *Embed) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

type EmbedField struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Inline        bool                   `protobuf:"varint,3,opt,name=inline,proto3" json:"inline,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbedField) Reset() {
	*x = EmbedField{}
	mi := &file_types_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbedField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbedField) ProtoMessage() {}

func (x *EmbedField) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbedField.ProtoReflect.Descriptor instead.
func (*EmbedField) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{5}
}

func (x *EmbedField) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EmbedField) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *EmbedField) GetInline() bool {
	if x != nil {
		return x.Inline
	}
	return false
}

// Channel events
type ChannelCreatedPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channel       *Channel               `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelCreatedPayload) Reset() {
	*x = ChannelCreatedPayload{}
	mi := &file_types_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelCreatedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelCreatedPayload) ProtoMessage() {}

func (x *ChannelCreatedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelCreatedPayload.ProtoReflect.Descriptor instead.
func (*ChannelCreatedPayload) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{6}
}

func (x *ChannelCreatedPayload) GetChannel() *Channel {
	if x != nil {
		return x.Channel
	}
	return nil
}

type ChannelUpdatedPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channel       *Channel               `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	ChangedFields []string               `protobuf:"bytes,2,rep,name=changed_fields,json=changedFields,proto3" json:"changed_fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelUpdatedPayload) Reset() {
	*x = ChannelUpdatedPayload{}
	mi := &file_types_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelUpdatedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelUpdatedPayload) ProtoMessage() {}

func (x *ChannelUpdatedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelUpdatedPayload.ProtoReflect.Descriptor instead.
func (*ChannelUpdatedPayload) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{7}
}

func (x *ChannelUpdatedPayload) GetChannel() *Channel {
	if x != nil {
		return x.Channel
	}
	return nil
}

func (x *ChannelUpdatedPayload) GetChangedFields() []string {
	if x != nil {
		return x.ChangedFields
	}
	return nil
}

type ChannelDeletedPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	ServerId      string                 `protobuf:"bytes,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelDeletedPayload) Reset() {
	*x = ChannelDeletedPayload{}
	mi := &file_types_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelDeletedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelDeletedPayload) ProtoMessage() {}

func (x *ChannelDeletedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelDeletedPayload.ProtoReflect.Descriptor instead.
func (*ChannelDeletedPayload) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{8}
}

func (x *ChannelDeletedPayload) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *ChannelDeletedPayload) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

// Message events
type MessageSentPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *Message               `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageSentPayload) Reset() {
	*x = MessageSentPayload{}
	mi := &file_types_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageSentPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageSentPayload) ProtoMessage() {}

func (x *MessageSentPayload) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageSentPayload.ProtoReflect.Descriptor instead.
func (*MessageSentPayload) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{9}
}

func (x *MessageSentPayload) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

type MessageUpdatedPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *Message               `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	ChangedFields []string               `protobuf:"bytes,2,rep,name=changed_fields,json=changedFields,proto3" json:"changed_fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageUpdatedPayload) Reset() {
	*x = MessageUpdatedPayload{}
	mi := &file_types_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageUpdatedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageUpdatedPayload) ProtoMessage() {}

func (x *MessageUpdatedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageUpdatedPayload.ProtoReflect.Descriptor instead.
func (*MessageUpdatedPayload) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{10}
}

func (x *MessageUpdatedPayload) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *MessageUpdatedPayload) GetChangedFields() []string {
	if x != nil {
		return x.ChangedFields
	}
	return nil
}

type MessageDeletedPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	ChannelId     string                 `protobuf:"bytes,2,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageDeletedPayload) Reset() {
	*x = MessageDeletedPayload{}
	mi := &file_types_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageDeletedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageDeletedPayload) ProtoMessage() {}

func (x *MessageDeletedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageDeletedPayload.ProtoReflect.Descriptor instead.
func (*MessageDeletedPayload) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{11}
}

func (x *MessageDeletedPayload) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *MessageDeletedPayload) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

type ConfigUpdatedPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scope         string                 `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	OldValue      *ConfigValue           `protobuf:"bytes,3,opt,name=old_value,json=oldValue,proto3" json:"old_value,omitempty"`
	NewValue      *ConfigValue           `protobuf:"bytes,4,opt,name=new_value,json=newValue,proto3" json:"new_value,omitempty"`
	UpdatedBy     string                 `protobuf:"bytes,5,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigUpdatedPayload) Reset() {
	*x = ConfigUpdatedPayload{}
	mi := &file_types_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigUpdatedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigUpdatedPayload) ProtoMessage() {}

func (x *ConfigUpdatedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigUpdatedPayload.ProtoReflect.Descriptor instead.
func (*ConfigUpdatedPayload) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{12}
}

func (x *ConfigUpdatedPayload) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *ConfigUpdatedPayload) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ConfigUpdatedPayload) GetOldValue() *ConfigValue {
	if x != nil {
		return x.OldValue
	}
	return nil
}

func (x *ConfigUpdatedPayload) GetNewValue() *ConfigValue {
	if x != nil {
		return x.NewValue
	}
	return nil
}

func (x *ConfigUpdatedPayload) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

func (x *ConfigUpdatedPayload) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ConfigUpdatedPayload) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type ConfigDeletedPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scope         string                 `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	DeletedValue  *ConfigValue           `protobuf:"bytes,3,opt,name=deleted_value,json=deletedValue,proto3" json:"deleted_value,omitempty"`
	DeletedBy     string                 `protobuf:"bytes,4,opt,name=deleted_by,json=deletedBy,proto3" json:"deleted_by,omitempty"`
	Reason        string                 `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigDeletedPayload) Reset() {
	*x = ConfigDeletedPayload{}
	mi := &file_types_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigDeletedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigDeletedPayload) ProtoMessage() {}

func (x *ConfigDeletedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigDeletedPayload.ProtoReflect.Descriptor instead.
func (*ConfigDeletedPayload) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{13}
}

func (x *ConfigDeletedPayload) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *ConfigDeletedPayload) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ConfigDeletedPayload) GetDeletedValue() *ConfigValue {
	if x != nil {
		return x.DeletedValue
	}
	return nil
}

func (x *ConfigDeletedPayload) GetDeletedBy() string {
	if x != nil {
		return x.DeletedBy
	}
	return ""
}

func (x *ConfigDeletedPayload) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ConfigDeletedPayload) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// Config value types for the config service
type ConfigValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*ConfigValue_StringValue
	//	*ConfigValue_IntValue
	//	*ConfigValue_FloatValue
	//	*ConfigValue_BoolValue
	//	*ConfigValue_ObjectValue
	//	*ConfigValue_ArrayValue
	Value         isConfigValue_Value `protobuf_oneof:"value"`
	Type          ConfigValueType     `protobuf:"varint,7,opt,name=type,proto3,enum=fuwa.ConfigValueType" json:"type,omitempty"`
	IsSensitive   bool                `protobuf:"varint,8,opt,name=is_sensitive,json=isSensitive,proto3" json:"is_sensitive,omitempty"`
	Constraints   *ConfigConstraints  `protobuf:"bytes,9,opt,name=constraints,proto3" json:"constraints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigValue) Reset() {
	*x = ConfigValue{}
	mi := &file_types_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigValue) ProtoMessage() {}

func (x *ConfigValue) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigValue.ProtoReflect.Descriptor instead.
func (*ConfigValue) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{14}
}

func (x *ConfigValue) GetValue() isConfigValue_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *ConfigValue) GetStringValue() string {
	if x != nil {
		if x, ok := x.Value.(*ConfigValue_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *ConfigValue) GetIntValue() int64 {
	if x != nil {
		if x, ok := x.Value.(*ConfigValue_IntValue); ok {
			return x.IntValue
		}
	}
	return 0
}

func (x *ConfigValue) GetFloatValue() float64 {
	if x != nil {
		if x, ok := x.Value.(*ConfigValue_FloatValue); ok {
			return x.FloatValue
		}
	}
	return 0
}

func (x *ConfigValue) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Value.(*ConfigValue_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

func (x *ConfigValue) GetObjectValue() *ConfigObject {
	if x != nil {
		if x, ok := x.Value.(*ConfigValue_ObjectValue); ok {
			return x.ObjectValue
		}
	}
	return nil
}

func (x *ConfigValue) GetArrayValue() *ConfigArray {
	if x != nil {
		if x, ok := x.Value.(*ConfigValue_ArrayValue); ok {
			return x.ArrayValue
		}
	}
	return nil
}

func (x *ConfigValue) GetType() ConfigValueType {
	if x != nil {
		return x.Type
	}
	return ConfigValueType_CONFIG_VALUE_TYPE_UNSPECIFIED
}

func (x *ConfigValue) GetIsSensitive() bool {
	if x != nil {
		return x.IsSensitive
	}
	return false
}

func (x *ConfigValue) GetConstraints() *ConfigConstraints {
	if x != nil {
		return x.Constraints
	}
	return nil
}

type isConfigValue_Value interface {
	isConfigValue_Value()
}

type ConfigValue_StringValue struct {
	StringValue string `protobuf:"bytes,1,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type ConfigValue_IntValue struct {
	IntValue int64 `protobuf:"varint,2,opt,name=int_value,json=intValue,proto3,oneof"`
}

type ConfigValue_FloatValue struct {
	FloatValue float64 `protobuf:"fixed64,3,opt,name=float_value,json=floatValue,proto3,oneof"`
}

type ConfigValue_BoolValue struct {
	BoolValue bool `protobuf:"varint,4,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

type ConfigValue_ObjectValue struct {
	ObjectValue *ConfigObject `protobuf:"bytes,5,opt,name=object_value,json=objectValue,proto3,oneof"`
}

type ConfigValue_ArrayValue struct {
	ArrayValue *ConfigArray `protobuf:"bytes,6,opt,name=array_value,json=arrayValue,proto3,oneof"`
}

func (*ConfigValue_StringValue) isConfigValue_Value() {}

func (*ConfigValue_IntValue) isConfigValue_Value() {}

func (*ConfigValue_FloatValue) isConfigValue_Value() {}

func (*ConfigValue_BoolValue) isConfigValue_Value() {}

func (*ConfigValue_ObjectValue) isConfigValue_Value() {}

func (*ConfigValue_ArrayValue) isConfigValue_Value() {}

type ConfigObject struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Fields        map[string]*ConfigValue `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigObject) Reset() {
	*x = ConfigObject{}
	mi := &file_types_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigObject) ProtoMessage() {}

func (x *ConfigObject) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigObject.ProtoReflect.Descriptor instead.
func (*ConfigObject) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{15}
}

func (x *ConfigObject) GetFields() map[string]*ConfigValue {
	if x != nil {
		return x.Fields
	}
	return nil
}

type ConfigArray struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ConfigValue         `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigArray) Reset() {
	*x = ConfigArray{}
	mi := &file_types_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigArray) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigArray) ProtoMessage() {}

func (x *ConfigArray) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigArray.ProtoReflect.Descriptor instead.
func (*ConfigArray) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{16}
}

func (x *ConfigArray) GetItems() []*ConfigValue {
	if x != nil {
		return x.Items
	}
	return nil
}

type ConfigConstraints struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MinLength     int32                  `protobuf:"varint,1,opt,name=min_length,json=minLength,proto3" json:"min_length,omitempty"`
	MaxLength     int32                  `protobuf:"varint,2,opt,name=max_length,json=maxLength,proto3" json:"max_length,omitempty"`
	Pattern       string                 `protobuf:"bytes,3,opt,name=pattern,proto3" json:"pattern,omitempty"`
	AllowedValues []string               `protobuf:"bytes,4,rep,name=allowed_values,json=allowedValues,proto3" json:"allowed_values,omitempty"`
	MinValue      float64                `protobuf:"fixed64,5,opt,name=min_value,json=minValue,proto3" json:"min_value,omitempty"`
	MaxValue      float64                `protobuf:"fixed64,6,opt,name=max_value,json=maxValue,proto3" json:"max_value,omitempty"`
	MinItems      int32                  `protobuf:"varint,7,opt,name=min_items,json=minItems,proto3" json:"min_items,omitempty"`
	MaxItems      int32                  `protobuf:"varint,8,opt,name=max_items,json=maxItems,proto3" json:"max_items,omitempty"`
	Required      bool                   `protobuf:"varint,9,opt,name=required,proto3" json:"required,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigConstraints) Reset() {
	*x = ConfigConstraints{}
	mi := &file_types_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigConstraints) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigConstraints) ProtoMessage() {}

func (x *ConfigConstraints) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigConstraints.ProtoReflect.Descriptor instead.
func (*ConfigConstraints) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{17}
}

func (x *ConfigConstraints) GetMinLength() int32 {
	if x != nil {
		return x.MinLength
	}
	return 0
}

func (x *ConfigConstraints) GetMaxLength() int32 {
	if x != nil {
		return x.MaxLength
	}
	return 0
}

func (x *ConfigConstraints) GetPattern() string {
	if x != nil {
		return x.Pattern
	}
	return ""
}

func (x *ConfigConstraints) GetAllowedValues() []string {
	if x != nil {
		return x.AllowedValues
	}
	return nil
}

func (x *ConfigConstraints) GetMinValue() float64 {
	if x != nil {
		return x.MinValue
	}
	return 0
}

func (x *ConfigConstraints) GetMaxValue() float64 {
	if x != nil {
		return x.MaxValue
	}
	return 0
}

func (x *ConfigConstraints) GetMinItems() int32 {
	if x != nil {
		return x.MinItems
	}
	return 0
}

func (x *ConfigConstraints) GetMaxItems() int32 {
	if x != nil {
		return x.MaxItems
	}
	return 0
}

func (x *ConfigConstraints) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

var File_types_proto protoreflect.FileDescriptor

const file_types_proto_rawDesc = "" +
	"\n" +
	"\vtypes.proto\x12\x04fuwa\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x19google/protobuf/any.proto\"\xec\x02\n" +
	"\x05Event\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x12\x14\n" +
	"\x05scope\x18\x03 \x01(\tR\x05scope\x12\x19\n" +
	"\bactor_id\x18\x04 \x01(\tR\aactorId\x128\n" +
	"\ttimestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12.\n" +
	"\apayload\x18\x06 \x01(\v2\x14.google.protobuf.AnyR\apayload\x125\n" +
	"\bmetadata\x18\a \x03(\v2\x19.fuwa.Event.MetadataEntryR\bmetadata\x12\x1a\n" +
	"\bsequence\x18\b \x01(\x03R\bsequence\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x89\x03\n" +
	"\aChannel\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12%\n" +
	"\x04type\x18\x03 \x01(\x0e2\x11.fuwa.ChannelTypeR\x04type\x12\x1b\n" +
	"\tserver_id\x18\x04 \x01(\tR\bserverId\x12\x1b\n" +
	"\tparent_id\x18\x05 \x01(\tR\bparentId\x127\n" +
	"\bmetadata\x18\x06 \x03(\v2\x1b.fuwa.Channel.MetadataEntryR\bmetadata\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xed\x02\n" +
	"\aMessage\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x02 \x01(\tR\tchannelId\x12\x1b\n" +
	"\tauthor_id\x18\x03 \x01(\tR\bauthorId\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x122\n" +
	"\vattachments\x18\x05 \x03(\v2\x10.fuwa.AttachmentR\vattachments\x12#\n" +
	"\x06embeds\x18\x06 \x03(\v2\v.fuwa.EmbedR\x06embeds\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1e\n" +
	"\vreply_to_id\x18\t \x01(\tR\treplyToId\"\x96\x01\n" +
	"\n" +
	"Attachment\x12#\n" +
	"\rattachment_id\x18\x01 \x01(\tR\fattachmentId\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentType\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x03R\x04size\x12\x10\n" +
	"\x03url\x18\x05 \x01(\tR\x03url\"\xd3\x01\n" +
	"\x05Embed\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12\x14\n" +
	"\x05color\x18\x04 \x01(\x05R\x05color\x12(\n" +
	"\x06fields\x18\x05 \x03(\v2\x10.fuwa.EmbedFieldR\x06fields\x12#\n" +
	"\rthumbnail_url\x18\x06 \x01(\tR\fthumbnailUrl\x12\x1b\n" +
	"\timage_url\x18\a \x01(\tR\bimageUrl\"N\n" +
	"\n" +
	"EmbedField\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x16\n" +
	"\x06inline\x18\x03 \x01(\bR\x06inline\"@\n" +
	"\x15ChannelCreatedPayload\x12'\n" +
	"\achannel\x18\x01 \x01(\v2\r.fuwa.ChannelR\achannel\"g\n" +
	"\x15ChannelUpdatedPayload\x12'\n" +
	"\achannel\x18\x01 \x01(\v2\r.fuwa.ChannelR\achannel\x12%\n" +
	"\x0echanged_fields\x18\x02 \x03(\tR\rchangedFields\"S\n" +
	"\x15ChannelDeletedPayload\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\x12\x1b\n" +
	"\tserver_id\x18\x02 \x01(\tR\bserverId\"=\n" +
	"\x12MessageSentPayload\x12'\n" +
	"\amessage\x18\x01 \x01(\v2\r.fuwa.MessageR\amessage\"g\n" +
	"\x15MessageUpdatedPayload\x12'\n" +
	"\amessage\x18\x01 \x01(\v2\r.fuwa.MessageR\amessage\x12%\n" +
	"\x0echanged_fields\x18\x02 \x03(\tR\rchangedFields\"U\n" +
	"\x15MessageDeletedPayload\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x02 \x01(\tR\tchannelId\"\x99\x02\n" +
	"\x14ConfigUpdatedPayload\x12\x14\n" +
	"\x05scope\x18\x01 \x01(\tR\x05scope\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12.\n" +
	"\told_value\x18\x03 \x01(\v2\x11.fuwa.ConfigValueR\boldValue\x12.\n" +
	"\tnew_value\x18\x04 \x01(\v2\x11.fuwa.ConfigValueR\bnewValue\x12\x1d\n" +
	"\n" +
	"updated_by\x18\x05 \x01(\tR\tupdatedBy\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x128\n" +
	"\ttimestamp\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\xe7\x01\n" +
	"\x14ConfigDeletedPayload\x12\x14\n" +
	"\x05scope\x18\x01 \x01(\tR\x05scope\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x126\n" +
	"\rdeleted_value\x18\x03 \x01(\v2\x11.fuwa.ConfigValueR\fdeletedValue\x12\x1d\n" +
	"\n" +
	"deleted_by\x18\x04 \x01(\tR\tdeletedBy\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\x128\n" +
	"\ttimestamp\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\x96\x03\n" +
	"\vConfigValue\x12#\n" +
	"\fstring_value\x18\x01 \x01(\tH\x00R\vstringValue\x12\x1d\n" +
	"\tint_value\x18\x02 \x01(\x03H\x00R\bintValue\x12!\n" +
	"\vfloat_value\x18\x03 \x01(\x01H\x00R\n" +
	"floatValue\x12\x1f\n" +
	"\n" +
	"bool_value\x18\x04 \x01(\bH\x00R\tboolValue\x127\n" +
	"\fobject_value\x18\x05 \x01(\v2\x12.fuwa.ConfigObjectH\x00R\vobjectValue\x124\n" +
	"\varray_value\x18\x06 \x01(\v2\x11.fuwa.ConfigArrayH\x00R\n" +
	"arrayValue\x12)\n" +
	"\x04type\x18\a \x01(\x0e2\x15.fuwa.ConfigValueTypeR\x04type\x12!\n" +
	"\fis_sensitive\x18\b \x01(\bR\visSensitive\x129\n" +
	"\vconstraints\x18\t \x01(\v2\x17.fuwa.ConfigConstraintsR\vconstraintsB\a\n" +
	"\x05value\"\x94\x01\n" +
	"\fConfigObject\x126\n" +
	"\x06fields\x18\x01 \x03(\v2\x1e.fuwa.ConfigObject.FieldsEntryR\x06fields\x1aL\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12'\n" +
	"\x05value\x18\x02 \x01(\v2\x11.fuwa.ConfigValueR\x05value:\x028\x01\"6\n" +
	"\vConfigArray\x12'\n" +
	"\x05items\x18\x01 \x03(\v2\x11.fuwa.ConfigValueR\x05items\"\xa2\x02\n" +
	"\x11ConfigConstraints\x12\x1d\n" +
	"\n" +
	"min_length\x18\x01 \x01(\x05R\tminLength\x12\x1d\n" +
	"\n" +
	"max_length\x18\x02 \x01(\x05R\tmaxLength\x12\x18\n" +
	"\apattern\x18\x03 \x01(\tR\apattern\x12%\n" +
	"\x0eallowed_values\x18\x04 \x03(\tR\rallowedValues\x12\x1b\n" +
	"\tmin_value\x18\x05 \x01(\x01R\bminValue\x12\x1b\n" +
	"\tmax_value\x18\x06 \x01(\x01R\bmaxValue\x12\x1b\n" +
	"\tmin_items\x18\a \x01(\x05R\bminItems\x12\x1b\n" +
	"\tmax_items\x18\b \x01(\x05R\bmaxItems\x12\x1a\n" +
	"\brequired\x18\t \x01(\bR\brequired*\x92\x01\n" +
	"\vChannelType\x12\x1c\n" +
	"\x18CHANNEL_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11CHANNEL_TYPE_TEXT\x10\x01\x12\x16\n" +
	"\x12CHANNEL_TYPE_VOICE\x10\x02\x12\x1d\n" +
	"\x19CHANNEL_TYPE_ANNOUNCEMENT\x10\x03\x12\x17\n" +
	"\x13CHANNEL_TYPE_THREAD\x10\x04*\xe1\x01\n" +
	"\x0fConfigValueType\x12!\n" +
	"\x1dCONFIG_VALUE_TYPE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18CONFIG_VALUE_TYPE_STRING\x10\x01\x12\x19\n" +
	"\x15CONFIG_VALUE_TYPE_INT\x10\x02\x12\x1b\n" +
	"\x17CONFIG_VALUE_TYPE_FLOAT\x10\x03\x12\x1a\n" +
	"\x16CONFIG_VALUE_TYPE_BOOL\x10\x04\x12\x1c\n" +
	"\x18CONFIG_VALUE_TYPE_OBJECT\x10\x05\x12\x1b\n" +
	"\x17CONFIG_VALUE_TYPE_ARRAY\x10\x06B\"Z github.com/waifu-devs/fuwa/protob\x06proto3"

var (
	file_types_proto_rawDescOnce sync.Once
	file_types_proto_rawDescData []byte
)

func file_types_proto_rawDescGZIP() []byte {
	file_types_proto_rawDescOnce.Do(func() {
		file_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_types_proto_rawDesc), len(file_types_proto_rawDesc)))
	})
	return file_types_proto_rawDescData
}

var file_types_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_types_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_types_proto_goTypes = []any{
	(ChannelType)(0),              // 0: fuwa.ChannelType
	(ConfigValueType)(0),          // 1: fuwa.ConfigValueType
	(*Event)(nil),                 // 2: fuwa.Event
	(*Channel)(nil),               // 3: fuwa.Channel
	(*Message)(nil),               // 4: fuwa.Message
	(*Attachment)(nil),            // 5: fuwa.Attachment
	(*Embed)(nil),                 // 6: fuwa.Embed
	(*EmbedField)(nil),            // 7: fuwa.EmbedField
	(*ChannelCreatedPayload)(nil), // 8: fuwa.ChannelCreatedPayload
	(*ChannelUpdatedPayload)(nil), // 9: fuwa.ChannelUpdatedPayload
	(*ChannelDeletedPayload)(nil), // 10: fuwa.ChannelDeletedPayload
	(*MessageSentPayload)(nil),    // 11: fuwa.MessageSentPayload
	(*MessageUpdatedPayload)(nil), // 12: fuwa.MessageUpdatedPayload
	(*MessageDeletedPayload)(nil), // 13: fuwa.MessageDeletedPayload
	(*ConfigUpdatedPayload)(nil),  // 14: fuwa.ConfigUpdatedPayload
	(*ConfigDeletedPayload)(nil),  // 15: fuwa.ConfigDeletedPayload
	(*ConfigValue)(nil),           // 16: fuwa.ConfigValue
	(*ConfigObject)(nil),          // 17: fuwa.ConfigObject
	(*ConfigArray)(nil),           // 18: fuwa.ConfigArray
	(*ConfigConstraints)(nil),     // 19: fuwa.ConfigConstraints
	nil,                           // 20: fuwa.Event.MetadataEntry
	nil,                           // 21: fuwa.Channel.MetadataEntry
	nil,                           // 22: fuwa.ConfigObject.FieldsEntry
	(*timestamppb.Timestamp)(nil), // 23: google.protobuf.Timestamp
	(*anypb.Any)(nil),             // 24: google.protobuf.Any
}
var file_types_proto_depIdxs = []int32{
	23, // 0: fuwa.Event.timestamp:type_name -> google.protobuf.Timestamp
	24, // 1: fuwa.Event.payload:type_name -> google.protobuf.Any
	20, // 2: fuwa.Event.metadata:type_name -> fuwa.Event.MetadataEntry
	0,  // 3: fuwa.Channel.type:type_name -> fuwa.ChannelType
	21, // 4: fuwa.Channel.metadata:type_name -> fuwa.Channel.MetadataEntry
	23, // 5: fuwa.Channel.created_at:type_name -> google.protobuf.Timestamp
	23, // 6: fuwa.Channel.updated_at:type_name -> google.protobuf.Timestamp
	5,  // 7: fuwa.Message.attachments:type_name -> fuwa.Attachment
	6,  // 8: fuwa.Message.embeds:type_name -> fuwa.Embed
	23, // 9: fuwa.Message.created_at:type_name -> google.protobuf.Timestamp
	23, // 10: fuwa.Message.updated_at:type_name -> google.protobuf.Timestamp
	7,  // 11: fuwa.Embed.fields:type_name -> fuwa.EmbedField
	3,  // 12: fuwa.ChannelCreatedPayload.channel:type_name -> fuwa.Channel
	3,  // 13: fuwa.ChannelUpdatedPayload.channel:type_name -> fuwa.Channel
	4,  // 14: fuwa.MessageSentPayload.message:type_name -> fuwa.Message
	4,  // 15: fuwa.MessageUpdatedPayload.message:type_name -> fuwa.Message
	16, // 16: fuwa.ConfigUpdatedPayload.old_value:type_name -> fuwa.ConfigValue
	16, // 17: fuwa.ConfigUpdatedPayload.new_value:type_name -> fuwa.ConfigValue
	23, // 18: fuwa.ConfigUpdatedPayload.timestamp:type_name -> google.protobuf.Timestamp
	16, // 19: fuwa.ConfigDeletedPayload.deleted_value:type_name -> fuwa.ConfigValue
	23, // 20: fuwa.ConfigDeletedPayload.timestamp:type_name -> google.protobuf.Timestamp
	17, // 21: fuwa.ConfigValue.object_value:type_name -> fuwa.ConfigObject
	18, // 22: fuwa.ConfigValue.array_value:type_name -> fuwa.ConfigArray
	1,  // 23: fuwa.ConfigValue.type:type_name -> fuwa.ConfigValueType
	19, // 24: fuwa.ConfigValue.constraints:type_name -> fuwa.ConfigConstraints
	22, // 25: fuwa.ConfigObject.fields:type_name -> fuwa.ConfigObject.FieldsEntry
	16, // 26: fuwa.ConfigArray.items:type_name -> fuwa.ConfigValue
	16, // 27: fuwa.ConfigObject.FieldsEntry.value:type_name -> fuwa.ConfigValue
	28, // [28:28] is the sub-list for method output_type
	28, // [28:28] is the sub-list for method input_type
	28, // [28:28] is the sub-list for extension type_name
	28, // [28:28] is the sub-list for extension extendee
	0,  // [0:28] is the sub-list for field type_name
}

func init() { file_types_proto_init() }
func file_types_proto_init() {
	if File_types_proto != nil {
		return
	}
	file_types_proto_msgTypes[14].OneofWrappers = []any{
		(*ConfigValue_StringValue)(nil),
		(*ConfigValue_IntValue)(nil),
		(*ConfigValue_FloatValue)(nil),
		(*ConfigValue_BoolValue)(nil),
		(*ConfigValue_ObjectValue)(nil),
		(*ConfigValue_ArrayValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_types_proto_rawDesc), len(file_types_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_types_proto_goTypes,
		DependencyIndexes: file_types_proto_depIdxs,
		EnumInfos:         file_types_proto_enumTypes,
		MessageInfos:      file_types_proto_msgTypes,
	}.Build()
	File_types_proto = out.File
	file_types_proto_goTypes = nil
	file_types_proto_depIdxs = nil
}
